### PR TITLE
Revert "Docker preserve sources"

### PR DESCRIPTION
**Pull request by mudler**
Reverts go-skynet/LocalAI#590

@samm81 this seems to break images - how did you tested it? See #615

### CODE REVIEW

**Comment by samm81** [comment]
that's strange - it worked for me locally & the checks all seemed to have passed - will take a closer look at #615 when I have  aminute

**Comment by samm81** [comment]
I wonder if it's something with `docker-compose` b/c I wasn't testing with that

**Comment by m4xw** [comment]
Been testing it since merge too and encountered no such issues on my end, mostly changing Makefile stuff & using docker directly

**Comment by samm81** [comment]
ok I figured out what's happening - I changed the final docker image to _only_ contain the `entrypoint.sh` script and the `local-ai` binary - so when `REBUILD=true` (which it is by default, but I always set it to `false` in my testing) it fails to be able to rebuild

I'll fix it up to preserve old behavior - but what is the intent of the `REBUILD` behavior? it seems like we should let `docker` take care of deciding to rebuild when the `Makefile` changes

**Comment by m4xw** [comment]
They use native optimizations when building so the public localai container they ship may not run on every pc (just crashes on my ryzen with undefined instruction for example), so for public distributions its kinda warranted to do at least once and commit the container.
For home builders like us it doesnt matter

**Pull request merged**
